name: Build shaded JAR

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'   
      - name: Build
        run: mvn -B -DskipTests -DskipJlink=true clean package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: book-tracker-app
          path: target/*-shaded.jar
